### PR TITLE
build.rs: use build_target()

### PR DESCRIPTION
**Pull request by mgeier**
Fixes #8.

I have learned about this `cmake-rs` feature in https://github.com/mgeier/libflac-sys/pull/5.

An even better solution will become available in the next `cmake-rs` release, see https://github.com/alexcrichton/cmake-rs/pull/105.

### CODE REVIEW

**Review by Prior99 — APPROVED** [review]

**Comment by Prior99** [comment]
Looks good, will merge and release this later. Thanks :)

**Comment by mgeier** [comment]
A new release of `cmake-rs` has just been made.

So it would probably be better if I use the new version in this PR (similar to https://github.com/mgeier/libflac-sys/pull/10)?

Except you don't want to depend on the very latest version of `cmake-rs`?

**Comment by Prior99** [comment]
That would be cool :)

**Comment by mgeier** [comment]
OK, done, I've used the approach from https://github.com/mgeier/libflac-sys/pull/10.

**Pull request merged**
